### ISSUE TITLE
Codespace does not initialize with all Python dependencies

### ISSUE THREAD

**Issue by royarin** [microsoft/aitour-exploring-cutting-edge-models#41]
Downloading scipy-1.11.1.tar.gz (56.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.0/56.0 MB 46.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      + meson setup /tmp/pip-install-_uhxxumf/scipy_f7aceb3732ed4260b2f3513903e47a5a /tmp/pip-install-_uhxxumf/scipy_f7aceb3732ed4260b2f3513903e47a5a/.mesonpy-h9kvz6kb/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-_uhxxumf/scipy_f7aceb3732ed4260b2f3513903e47a5a/.mesonpy-h9kvz6kb/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.6.0
      Source dir: /tmp/pip-install-_uhxxumf/scipy_f7aceb3732ed4260b2f3513903e47a5a
      Build dir: /tmp/pip-install-_uhxxumf/scipy_f7aceb3732ed4260b2f3513903e47a5a/.mesonpy-h9kvz6kb/build
      Build type: native build
      Project name: SciPy
      Project version: 1.11.1
      C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
      C linker for the host machine: cc ld.bfd 2.40
      C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian 12.2.0-14) 12.2.0")
      C++ linker for the host machine: c++ ld.bfd 2.40
      Cython compiler for the host machine: cython (cython 0.29.37)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (/opt/conda/bin/python3.12)
      Did not find pkg-config by name 'pkg-config'
      Found pkg-config: NO
      Run-time dependency python found: YES 3.12
      Program cython found: YES (/tmp/pip-build-env-3v3sqgj5/overlay/bin/cython)
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Library m found: YES
      
      ../../meson.build:82:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang-new'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --help` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang-new --help` gave "[Errno 2] No such file or directory: 'flang-new'"
      Running `flang-new --version` gave "[Errno 2] No such file or directory: 'flang-new'"
      Running `flang-new -V` gave "[Errno 2] No such file or directory: 'flang-new'"
      Running `flang --help` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --help` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --help` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --help` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --help` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --help` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /tmp/pip-install-_uhxxumf/scipy_f7aceb3732ed4260b2f3513903e47a5a/.mesonpy-h9kvz6kb/build/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by blackgrey0010** [comment]
@mbaiza27 can you please triage this issue with the correct folks

**Comment by leestott** [comment]
@royarin we will look into this but this should not cause any issues as scipy in a additional installed library and has no dependencies within the project or examples.

**Comment by leestott** [comment]
confirmed this library doesn't impact requirements will look at resolving dependencies and library versions.
